name: Python Package Workflow

on:
  workflow_call:
    inputs:
      python_version:
        description: "Python version to use"
        required: false
        default: "3.12.0"
        type: string

      install_dependencies_command:
        description: "Command to install dependencies"
        required: false
        default: "make dep"
        type: string

      build_command:
        description: "Command to build the package"
        required: false
        default: "make build"
        type: string

      dist_dir:
        description: "Dist directory"
        required: false
        default: "dist"
        type: string

    secrets:
      pypi_api_token:
        description: "PyPI token"
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.set_cache_key.outputs.CACHE_KEY }}
    steps:
      - name: Set cache key
        id: set_cache_key
        run: echo "CACHE_KEY=dist-${{ github.run_number }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install dependencies
        run: ${{ inputs.install_dependencies_command }}

      - name: Build
        run: ${{ inputs.build_command }}

      - name: Cache the build artifacts
        uses: actions/cache@v4
        with:
          path: ${{ inputs.dist_dir }}
          key: ${{ needs.setup.outputs.cache-key }}

  ensure-correct-pyproject-version:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Check and update version in pyproject.toml
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          PYPROJECT_VERSION=$(grep 'version =' pyproject.toml | awk -F'"' '{print $2}')
          if [ "$TAG_VERSION" != "$PYPROJECT_VERSION" ]; then
            sed -i "s/version = .*/version = '\"$TAG_VERSION\"'/" pyproject.toml
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add pyproject.toml
            git commit -m "Update version in pyproject.toml to $TAG_VERSION"
            git push
          else
            echo "Version in pyproject.toml matches the tag."

  pypi-publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [setup, build, ensure-correct-pyproject-version]
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: ${{ inputs.dist_dir }}
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_api_token }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [setup, build, ensure-correct-pyproject-version]
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: ${{ inputs.dist_dir }}
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: ${{ inputs.dist_dir }}/*
