name: Python Package Workflow

on:
  workflow_call:
    inputs:
      python_version:
        description: "Python version to use"
        required: false
        default: "3.12.0"
        type: string

      install_dependencies_command:
        description: "Command to install dependencies"
        required: false
        default: "make dep"
        type: string

      build_command:
        description: "Command to build the package"
        required: false
        default: "make build"
        type: string

      dist_dir:
        description: "Dist directory"
        required: false
        default: "dist"
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.set_cache_key.outputs.CACHE_KEY }}
    steps:
      - name: Set cache key
        id: set_cache_key
        run: echo "CACHE_KEY=dist-${{ github.run_number }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install dependencies
        run: ${{ inputs.install_dependencies_command }}

      - name: Build
        run: ${{ inputs.build_command }}

      - name: Cache the build artifacts
        uses: actions/cache@v4
        with:
          path: ${{ inputs.dist_dir }}
          key: ${{ needs.setup.outputs.cache-key }}

  pypi-publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [setup, build]
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: ${{ inputs.dist_dir }}
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [setup, build]
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: ${{ inputs.dist_dir }}
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: dist/*
